In [ ]:
!pip install -q transformers==5.16.1 datasets==5.0.1 accelerate==1.14.0 peft==0.20.0 bitsandbytes==0.50.2 trl==0.12.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 112.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 47.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 389.2/389.2 kB 37.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 775.8/775.8 kB 55.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 19.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.2/310.2 kB 27.8 MB/s eta 0:00:00

In [ ]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("VRAM:", round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2), "GB")

PyTorch version: 2.11.0+cu130
CUDA available: True
GPU: Tesla T4
VRAM: 14.56 GB

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

PROJECT_DIR = "/content/drive/MyDrive/OSTutorLLM"

TRAIN_FILE = os.path.join(PROJECT_DIR, "ostutorllm_train_270.json")
TEST_FILE = os.path.join(PROJECT_DIR, "ostutorllm_test_30.json")

print("Training file exists:", os.path.exists(TRAIN_FILE))
print("Test file exists:", os.path.exists(TEST_FILE))

print("\nTraining file:", TRAIN_FILE)
print("Test file:", TEST_FILE)

Training file exists: False
Test file exists: False

Training file: /content/drive/MyDrive/OSTutorLLM/ostutorllm_train_270.json
Test file: /content/drive/MyDrive/OSTutorLLM/ostutorllm_test_30.json

In [ ]:
import os

print("Files inside MyDrive/OSTutorLLM:")

folder = "/content/drive/MyDrive/OSTutorLLM"

if os.path.exists(folder):
    print(os.listdir(folder))
else:
    print("OSTutorLLM folder does not exist")

Files inside MyDrive/OSTutorLLM:
['ostutor_dataset', 'ostutor_qwen3_8b_test', 'os_dataset_50', 'ostutor_qwen3_8b_final']

In [ ]:
from google.colab import files

uploaded = files.upload()

print("\nUploaded files:")
for filename in uploaded:
    print(filename)

Saving ostutorllm_test_30.json to ostutorllm_test_30.json
Saving ostutorllm_train_270.json to ostutorllm_train_270.json

Uploaded files:
ostutorllm_test_30.json
ostutorllm_train_270.json

In [ ]:
import shutil
import os

PROJECT_DIR = "/content/drive/MyDrive/OSTutorLLM"

shutil.copy(
    "/content/ostutorllm_train_270.json",
    os.path.join(PROJECT_DIR, "ostutorllm_train_270.json")
)

shutil.copy(
    "/content/ostutorllm_test_30.json",
    os.path.join(PROJECT_DIR, "ostutorllm_test_30.json")
)

print("Datasets copied to Google Drive successfully!")

print("\nFiles now in OSTutorLLM:")
print(os.listdir(PROJECT_DIR))

Datasets copied to Google Drive successfully!

Files now in OSTutorLLM:
['ostutor_dataset', 'ostutor_qwen3_8b_test', 'os_dataset_50', 'ostutor_qwen3_8b_final', 'ostutorllm_train_270.json', 'ostutorllm_test_30.json']

In [ ]:
import json

with open(TRAIN_FILE, "r", encoding="utf-8") as f:
    train_data = json.load(f)

with open(TEST_FILE, "r", encoding="utf-8") as f:
    test_data = json.load(f)

print("Training examples:", len(train_data))
print("Test examples:", len(test_data))

print("\nFirst training example:")
print(train_data[0])

print("\nFirst test example:")
print(test_data[0])

Training examples: 270
Test examples: 30

First training example:
{'instruction': 'Explain process management in operating systems.', 'input': 'Explain it to a beginner.', 'output': "Process management is the operating system's job of creating, scheduling, and controlling processes. A process is a program that is currently running. The OS gives processes CPU time and manages their resources.", 'id': 1, 'split': 'train'}

First test example:
{'instruction': 'What is a shell in Linux?', 'input': 'Explain simply.', 'output': 'A shell is a command interpreter that accepts commands from a user and starts programs or performs system operations.', 'id': 271, 'split': 'test'}

In [ ]:
from datasets import Dataset

train_dataset = Dataset.from_list(train_data)

def convert_to_chat(example):
    user_message = example["instruction"]

    if example["input"]:
        user_message += "\n" + example["input"]

    return {
        "messages": [
            {
                "role": "user",
                "content": user_message
            },
            {
                "role": "assistant",
                "content": example["output"]
            }
        ]
    }

train_dataset = train_dataset.map(convert_to_chat)

print("Training dataset size:", len(train_dataset))
print("\nExample after conversion:")
print(train_dataset[0]["messages"])

Map:   0%|          | 0/270 [00:00<?, ? examples/s]

Training dataset size: 270

Example after conversion:
[{'content': 'Explain process management in operating systems.\nExplain it to a beginner.', 'role': 'user'}, {'content': "Process management is the operating system's job of creating, scheduling, and controlling processes. A process is a program that is currently running. The OS gives processes CPU time and manages their resources.", 'role': 'assistant'}]

In [ ]:
from transformers import AutoTokenizer

model_name = "Qwen/Qwen3-8B"

tokenizer = AutoTokenizer.from_pretrained(model_name)

print("Tokenizer loaded successfully!")
print("Model:", model_name)
print("Vocabulary size:", tokenizer.vocab_size)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/728 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/9.73k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

Tokenizer loaded successfully!
Model: Qwen/Qwen3-8B
Vocabulary size: 151643

In [ ]:
from transformers import AutoModelForCausalLM, BitsAndBytesConfig
import torch

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

print("Qwen3-8B loaded successfully!")

model.safetensors.index.json:   0%|          | 0.00/32.9k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/399 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Qwen3-8B loaded successfully!

In [ ]:
def format_chat(example):
    return {
        "text": tokenizer.apply_chat_template(
            example["messages"],
            tokenize=False,
            add_generation_prompt=False
        )
    }

train_dataset = train_dataset.map(format_chat)

print("Chat formatting completed!")
print("\nFormatted example:")
print(train_dataset[0]["text"][:1000])

Map:   0%|          | 0/270 [00:00<?, ? examples/s]

Chat formatting completed!

Formatted example:
<|im_start|>user
Explain process management in operating systems.
Explain it to a beginner.<|im_end|>
<|im_start|>assistant
<think>

</think>

Process management is the operating system's job of creating, scheduling, and controlling processes. A process is a program that is currently running. The OS gives processes CPU time and manages their resources.<|im_end|>

In [ ]:
from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj"
    ]
)

model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

trainable params: 15,335,424 || all params: 8,206,070,784 || trainable%: 0.1869

In [ ]:
from trl import SFTConfig

training_args = SFTConfig(
    output_dir="/content/ostutorllm_300_training",

    num_train_epochs=3,

    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,

    learning_rate=2e-4,

    logging_steps=1,
    save_strategy="epoch",

    fp16=False,
    bf16=False,

    max_seq_length=512,

    report_to="none"
)

print("SFT training configuration created successfully!")

SFT training configuration created successfully!

In [ ]:
from trl import SFTTrainer

trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    args=training_args,
)

print("SFTTrainer created successfully!")

Map:   0%|          | 0/270 [00:00<?, ? examples/s]

SFTTrainer created successfully!

In [ ]:
print("Starting OSTutorLLM fine-tuning...")
print("Training examples:", len(train_dataset))
print("Epochs:", training_args.num_train_epochs)

trainer.train()

print("\nTraining completed successfully!")

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Starting OSTutorLLM fine-tuning...
Training examples: 270
Epochs: 3

Training completed successfully!

In [ ]:
FINAL_ADAPTER_PATH = "/content/drive/MyDrive/OSTutorLLM/ostutor_qwen3_8b_300_final"

trainer.save_model(FINAL_ADAPTER_PATH)
tokenizer.save_pretrained(FINAL_ADAPTER_PATH)

print("Final 300-example LoRA adapter saved successfully!")
print("Saved to:", FINAL_ADAPTER_PATH)

Final 300-example LoRA adapter saved successfully!
Saved to: /content/drive/MyDrive/OSTutorLLM/ostutor_qwen3_8b_300_final

In [ ]:
import os

print("Checking saved adapter...\n")

if os.path.exists(FINAL_ADAPTER_PATH):
    print("✅ Adapter folder exists!")
    print("\nFiles saved:")

    for file in os.listdir(FINAL_ADAPTER_PATH):
        print(" -", file)
else:
    print("❌ Adapter folder was not found!")

Checking saved adapter...

✅ Adapter folder exists!

Files saved:
 - README.md
 - adapter_model.safetensors
 - adapter_config.json
 - chat_template.jinja
 - tokenizer_config.json
 - tokenizer.json
 - training_args.bin

In [ ]:
import json

with open(TEST_FILE, "r", encoding="utf-8") as f:
    test_data = json.load(f)

print("Held-out test examples:", len(test_data))

print("\nFirst test question:")
print(test_data[0]["instruction"])

print("\nExpected answer:")
print(test_data[0]["output"])

Held-out test examples: 30

First test question:
What is a shell in Linux?

Expected answer:
A shell is a command interpreter that accepts commands from a user and starts programs or performs system operations.

In [ ]:
import torch

model.eval()

question = test_data[0]["instruction"]

messages = [
    {
        "role": "user",
        "content": question
    }
]

text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

inputs = tokenizer(
    text,
    return_tensors="pt"
).to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=200,
        do_sample=False
    )

generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

answer = tokenizer.decode(
    generated_tokens,
    skip_special_tokens=True
)

print("QUESTION:")
print(question)

print("\nMODEL ANSWER:")
print(answer)

QUESTION:
What is a shell in Linux?

MODEL ANSWER:
<think>

</think>

A shell is a user interface that accepts commands and passes them to the operating system for execution. Common shells include bash, zsh, and sh.

In [ ]:
import re
import torch

model.eval()

results = []

for i, item in enumerate(test_data):
    question = item["instruction"]
    expected = item["output"]

    messages = [
        {
            "role": "user",
            "content": question
        }
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=200,
            do_sample=False
        )

    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

    answer = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    )

    results.append({
        "id": item.get("id", i + 1),
        "question": question,
        "expected": expected,
        "answer": answer
    })

    print(f"Completed {i+1}/30")

print("\n✅ Evaluation generation completed!")
print("Total test questions:", len(results))

Completed 1/30
Completed 2/30
Completed 3/30
Completed 4/30
Completed 5/30
Completed 6/30
Completed 7/30
Completed 8/30
Completed 9/30
Completed 10/30
Completed 11/30
Completed 12/30
Completed 13/30
Completed 14/30
Completed 15/30
Completed 16/30
Completed 17/30
Completed 18/30
Completed 19/30
Completed 20/30
Completed 21/30
Completed 22/30
Completed 23/30
Completed 24/30
Completed 25/30
Completed 26/30
Completed 27/30
Completed 28/30
Completed 29/30
Completed 30/30

✅ Evaluation generation completed!
Total test questions: 30

In [ ]:
for i, result in enumerate(results):
    print("=" * 80)
    print(f"QUESTION {i+1}")
    print("=" * 80)

    print("Q:", result["question"])
    print("\nEXPECTED:")
    print(result["expected"])

    print("\nMODEL ANSWER:")
    print(result["answer"])

    print(f"\nKeyword coverage: {result['concept_coverage']:.2f}%")

================================================================================
QUESTION 1
================================================================================
Q: What is a shell in Linux?

EXPECTED:
A shell is a command interpreter that accepts commands from a user and starts programs or performs system operations.

MODEL ANSWER:
<think>

</think>

A shell is a user interface that accepts commands and passes them to the operating system for execution. Common shells include bash, zsh, and sh.

Keyword coverage: 52.94%
================================================================================
QUESTION 2
================================================================================
Q: What does the Linux command pwd show?

EXPECTED:
The pwd command prints the current working directory.

MODEL ANSWER:
<think>

</think>

pwd stands for "print working directory" and prints the current directory path.

Keyword coverage: 85.71%
================================================================================
QUESTION 3
================================================================================
Q: What does the Linux command ls do?

EXPECTED:
The ls command lists files and directories in a directory.

MODEL ANSWER:
<think>

</think>

The ls command lists the contents of a directory.

Keyword coverage: 60.00%
================================================================================
QUESTION 4
================================================================================
Q: What does the Linux command cd do?

EXPECTED:
The cd command changes the current working directory.

MODEL ANSWER:
<think>

</think>

The cd command changes the current working directory.

Keyword coverage: 100.00%
================================================================================
QUESTION 5
================================================================================
Q: What does chmod do in Linux?

EXPECTED:
chmod changes the permission bits of a file or directory, controlling categories such as read, write, and execute access.

MODEL ANSWER:
<think>

</think>

chmod changes the permission bits of a file or directory. It can set read, write, and execute permissions for the owner, group, and others.

Keyword coverage: 73.68%
================================================================================
QUESTION 6
================================================================================
Q: What does ps show in Linux?

EXPECTED:
The ps command displays information about processes, such as process identifiers and execution status, depending on the options used.

MODEL ANSWER:
<think>

</think>

ps shows information about processes, such as process ID, state, owner, CPU and memory usage, and command.

Keyword coverage: 50.00%
================================================================================
QUESTION 7
================================================================================
Q: What does kill do in Linux?

EXPECTED:
The kill command sends a signal to a process identified by its PID. The signal can request actions such as termination, depending on the signal used.

MODEL ANSWER:
<think>

</think>

kill sends a signal to a process. The default signal is SIGTERM, which usually allows the process to clean up before termination.

Keyword coverage: 38.10%
================================================================================
QUESTION 8
================================================================================
Q: What is fork followed by exec used for?

EXPECTED:
A process can use fork to create a child and then exec in the child to replace its program image with another program. This is a common Unix process-creation pattern.

MODEL ANSWER:
<think>

</think>

Fork creates a child process, and exec replaces the child's image with a new program. This allows one process to start another program while retaining the parent's information.

Keyword coverage: 52.00%
================================================================================
QUESTION 9
================================================================================
Q: What is a shell pipeline?

EXPECTED:
A shell pipeline connects the output of one command to the input of another command, allowing commands to process data in stages.

MODEL ANSWER:
<think>

</think>

A shell pipeline connects the output of one command to the input of another, allowing commands to pass data through a sequence.

Keyword coverage: 83.33%
================================================================================
QUESTION 10
================================================================================
Q: What is the root directory in Linux?

EXPECTED:
The root directory is the top of the Linux file-system hierarchy and is represented by /.

MODEL ANSWER:
<think>

</think>

The root directory is the top-level directory of the file system hierarchy and is represented by the slash /.

Keyword coverage: 92.31%
================================================================================
QUESTION 11
================================================================================
Q: What is protection in an operating system?

EXPECTED:
Protection controls how processes and users access system resources so that one entity cannot improperly interfere with another.

MODEL ANSWER:
<think>

</think>

Protection is the mechanism used by an operating system to control access to resources so that only authorized processes can perform certain operations.

Keyword coverage: 38.89%
================================================================================
QUESTION 12
================================================================================
Q: What is authentication?

EXPECTED:
Authentication is the process of verifying the identity of a user or system, such as by a password, token, or biometric factor.

MODEL ANSWER:
<think>

</think>

Authentication is the process of verifying the identity of a user or system.

Keyword coverage: 61.11%
================================================================================
QUESTION 13
================================================================================
Q: What is authorization?

EXPECTED:
Authorization determines what an authenticated user or process is allowed to access or perform.

MODEL ANSWER:
<think>

</think>

Authorization determines what operations a user or process is allowed to perform on a resource after authentication has established identity.

Keyword coverage: 76.92%
================================================================================
QUESTION 14
================================================================================
Q: What is an access-control list?

EXPECTED:
An access-control list records permissions associated with a resource and identifies which users or groups can perform particular operations.

MODEL ANSWER:
<think>

</think>

An access-control list associates a permission list with an object and specifies which subjects have particular permissions.

Keyword coverage: 50.00%
================================================================================
QUESTION 15
================================================================================
Q: What is the principle of least privilege?

EXPECTED:
Least privilege means giving a user, process, or service only the permissions required to perform its legitimate tasks.

MODEL ANSWER:
<think>

</think>

The principle of least privilege gives a process only the permissions it needs to perform its task.

Keyword coverage: 55.56%
================================================================================
QUESTION 16
================================================================================
Q: What is a privilege escalation attack?

EXPECTED:
Privilege escalation occurs when an attacker or program gains permissions greater than those it was originally authorized to have.

MODEL ANSWER:
<think>

</think>

Privilege escalation occurs when an attacker gains higher privileges than they should have, allowing them to perform unauthorized operations.

Keyword coverage: 52.63%
================================================================================
QUESTION 17
================================================================================
Q: Why should operating systems isolate processes?

EXPECTED:
Process isolation limits accidental or malicious access to another process's memory and resources, improving security and reliability.

MODEL ANSWER:
<think>

</think>

Isolation prevents one process from directly corrupting or interfering with another process's data or execution.

Keyword coverage: 31.25%
================================================================================
QUESTION 18
================================================================================
Q: What is a secure boot concept?

EXPECTED:
Secure boot uses trusted components and cryptographic verification during startup to help prevent unauthorized or modified boot software from running.

MODEL ANSWER:
<think>

</think>

Secure boot ensures that only trusted software can load during the boot process, helping prevent unauthorized or malicious operating systems from running.

Keyword coverage: 52.63%
================================================================================
QUESTION 19
================================================================================
Q: What is an operating-system vulnerability?

EXPECTED:
An OS vulnerability is a weakness in the operating system that could be exploited to violate confidentiality, integrity, availability, or access controls.

MODEL ANSWER:
<think>

</think>

An operating-system vulnerability is a weakness in the OS that can be exploited by malicious software.

Keyword coverage: 59.09%
================================================================================
QUESTION 20
================================================================================
Q: Why are software updates important for operating-system security?

EXPECTED:
Updates can fix vulnerabilities, correct bugs, improve compatibility, and strengthen security mechanisms before known weaknesses are exploited.

MODEL ANSWER:
<think>

</think>

Software updates often include security patches that fix known vulnerabilities. Keeping the operating system up to date helps protect against attacks that exploit these vulnerabilities.

Keyword coverage: 29.41%
================================================================================
QUESTION 21
================================================================================
Q: What is a distributed operating system?

EXPECTED:
A distributed operating system manages resources across multiple connected computers and can provide users with a more integrated view of the distributed environment.

MODEL ANSWER:
<think>

</think>

A distributed operating system manages a collection of independent but interconnected computers and provides services that make them appear as a unified system.

Keyword coverage: 38.10%
================================================================================
QUESTION 22
================================================================================
Q: What is a real-time scheduling deadline?

EXPECTED:
A deadline is the latest acceptable time by which a real-time task should complete its required work.

MODEL ANSWER:
<think>

</think>

A deadline is the latest time by which a task must complete its critical execution.

Keyword coverage: 68.75%
================================================================================
QUESTION 23
================================================================================
Q: What is hard real-time scheduling?

EXPECTED:
Hard real-time systems require specified deadlines to be met; missing an important deadline may be considered a system failure.

MODEL ANSWER:
<think>

</think>

Hard real-time scheduling guarantees that critical tasks meet their deadlines even if the system is under load.

Keyword coverage: 26.32%
================================================================================
QUESTION 24
================================================================================
Q: What is soft real-time scheduling?

EXPECTED:
Soft real-time systems prefer tasks to meet deadlines, but occasional deadline misses may reduce quality rather than cause total system failure.

MODEL ANSWER:
<think>

</think>

Soft real-time scheduling allows tasks to tolerate occasional delays, but timely completion is preferred for acceptable system behavior.

Keyword coverage: 36.36%
================================================================================
QUESTION 25
================================================================================
Q: What is symmetric multiprocessing?

EXPECTED:
Symmetric multiprocessing uses multiple processors or cores that can generally perform operating-system and application work under a shared system design.

MODEL ANSWER:
<think>

</think>

Symmetric multiprocessing, or SMP, is a multiprocessor architecture in which multiple processors can execute operating-system tasks simultaneously.

Keyword coverage: 45.00%
================================================================================
QUESTION 26
================================================================================
Q: What is processor affinity?

EXPECTED:
Processor affinity is the preference or policy for keeping a process or thread on particular CPU cores, often to improve cache locality.

MODEL ANSWER:
<think>

</think>

Processor affinity is the tendency of a process to run on a particular CPU or set of CPUs. It can reduce migration overhead and improve cache reuse.

Keyword coverage: 61.90%
================================================================================
QUESTION 27
================================================================================
Q: What is load balancing in multiprocessor systems?

EXPECTED:
Load balancing distributes runnable work among processors so that no processor is unnecessarily idle while another is overloaded.

MODEL ANSWER:
<think>

</think>

Load balancing distributes work across processors to reduce idle time and improve overall system performance.

Keyword coverage: 35.29%
================================================================================
QUESTION 28
================================================================================
Q: What is NUMA?

EXPECTED:
NUMA, or Non-Uniform Memory Access, is a multiprocessor architecture in which memory-access time depends on which processor and memory region are involved.

MODEL ANSWER:
<think>

</think>

NUMA stands for Non-Uniform Memory Access. In a NUMA system, memory access time depends on whether the memory is local to the processor or located on another node.

Keyword coverage: 65.00%
================================================================================
QUESTION 29
================================================================================
Q: What is an embedded operating system?

EXPECTED:
An embedded operating system is designed for specialized devices with constrained resources and specific functions, such as controllers and appliances.

MODEL ANSWER:
<think>

</think>

An embedded operating system is designed to run on an embedded device and provides the necessary services for the device's specific application.

Keyword coverage: 47.37%
================================================================================
QUESTION 30
================================================================================
Q: What is an OS API?

EXPECTED:
An operating-system API is a set of programming interfaces through which applications request operating-system services, often implemented using system calls.

MODEL ANSWER:
<think>

</think>

An OS API provides a programmatic interface that allows applications to request OS services such as process creation, file operations, and memory management.

Keyword coverage: 31.58%

In [ ]:
import pandas as pd

evaluation_df = pd.DataFrame([
    {
        "Question": r["question"],
        "Expected Answer": r["expected"],
        "Model Answer": r["answer"],
        "Keyword Coverage (%)": round(r["concept_coverage"], 2)
    }
    for r in results
])

print("Evaluation table created!")
print("Number of test questions:", len(evaluation_df))

display(evaluation_df)

Evaluation table created!
Number of test questions: 30

,Question,Expected Answer,Model Answer,Keyword Coverage (%)
0,What is a shell in Linux?,A shell is a command interpreter that accepts ...,<think>\n\n</think>\n\nA shell is a user inter...,52.94
1,What does the Linux command pwd show?,The pwd command prints the current working dir...,"<think>\n\n</think>\n\npwd stands for ""print w...",85.71
2,What does the Linux command ls do?,The ls command lists files and directories in ...,<think>\n\n</think>\n\nThe ls command lists th...,60.00
3,What does the Linux command cd do?,The cd command changes the current working dir...,<think>\n\n</think>\n\nThe cd command changes ...,100.00
4,What does chmod do in Linux?,chmod changes the permission bits of a file or...,<think>\n\n</think>\n\nchmod changes the permi...,73.68
5,What does ps show in Linux?,The ps command displays information about proc...,<think>\n\n</think>\n\nps shows information ab...,50.00
6,What does kill do in Linux?,The kill command sends a signal to a process i...,<think>\n\n</think>\n\nkill sends a signal to ...,38.10
7,What is fork followed by exec used for?,A process can use fork to create a child and t...,<think>\n\n</think>\n\nFork creates a child pr...,52.00
8,What is a shell pipeline?,A shell pipeline connects the output of one co...,<think>\n\n</think>\n\nA shell pipeline connec...,83.33
9,What is the root directory in Linux?,The root directory is the top of the Linux fil...,<think>\n\n</think>\n\nThe root directory is t...,92.31
10,What is protection in an operating system?,Protection controls how processes and users ac...,<think>\n\n</think>\n\nProtection is the mecha...,38.89
11,What is authentication?,Authentication is the process of verifying the...,<think>\n\n</think>\n\nAuthentication is the p...,61.11
12,What is authorization?,Authorization determines what an authenticated...,<think>\n\n</think>\n\nAuthorization determine...,76.92
13,What is an access-control list?,An access-control list records permissions ass...,<think>\n\n</think>\n\nAn access-control list ...,50.00
14,What is the principle of least privilege?,"Least privilege means giving a user, process, ...",<think>\n\n</think>\n\nThe principle of least ...,55.56
15,What is a privilege escalation attack?,Privilege escalation occurs when an attacker o...,<think>\n\n</think>\n\nPrivilege escalation oc...,52.63
16,Why should operating systems isolate processes?,Process isolation limits accidental or malicio...,<think>\n\n</think>\n\nIsolation prevents one ...,31.25
17,What is a secure boot concept?,Secure boot uses trusted components and crypto...,<think>\n\n</think>\n\nSecure boot ensures tha...,52.63
18,What is an operating-system vulnerability?,An OS vulnerability is a weakness in the opera...,<think>\n\n</think>\n\nAn operating-system vul...,59.09
19,Why are software updates important for operati...,"Updates can fix vulnerabilities, correct bugs,...",<think>\n\n</think>\n\nSoftware updates often ...,29.41
20,What is a distributed operating system?,A distributed operating system manages resourc...,<think>\n\n</think>\n\nA distributed operating...,38.10
21,What is a real-time scheduling deadline?,A deadline is the latest acceptable time by wh...,<think>\n\n</think>\n\nA deadline is the lates...,68.75
22,What is hard real-time scheduling?,Hard real-time systems require specified deadl...,<think>\n\n</think>\n\nHard real-time scheduli...,26.32
23,What is soft real-time scheduling?,Soft real-time systems prefer tasks to meet de...,<think>\n\n</think>\n\nSoft real-time scheduli...,36.36
24,What is symmetric multiprocessing?,Symmetric multiprocessing uses multiple proces...,<think>\n\n</think>\n\nSymmetric multiprocessi...,45.00
25,What is processor affinity?,Processor affinity is the preference or policy...,<think>\n\n</think>\n\nProcessor affinity is t...,61.90
26,What is load balancing in multiprocessor systems?,Load balancing distributes runnable work among...,<think>\n\n</think>\n\nLoad balancing distribu...,35.29
27,What is NUMA?,"NUMA, or Non-Uniform Memory Access, is a multi...",<think>\n\n</think>\n\nNUMA stands for Non-Uni...,65.00
28,What is an embedded operating system?,An embedded operating system is designed for s...,<think>\n\n</think>\n\nAn embedded operating s...,47.37
29,What is an OS API?,An operating-system API is a set of programmin...,<think>\n\n</think>\n\nAn OS API provides a pr...,31.58

In [ ]:
EVAL_FILE = "/content/drive/MyDrive/OSTutorLLM/ostutorllm_30_test_evaluation.csv"

evaluation_df.to_csv(EVAL_FILE, index=False)

print("Evaluation results saved successfully!")
print("File:", EVAL_FILE)
print("Rows:", len(evaluation_df))

Evaluation results saved successfully!
File: /content/drive/MyDrive/OSTutorLLM/ostutorllm_30_test_evaluation.csv
Rows: 30

In [ ]:
evaluation_df["Semantic Score (0-2)"] = None
evaluation_df["Reason"] = ""

print("Semantic scoring columns added.")
display(
    evaluation_df[
        ["Question", "Model Answer", "Semantic Score (0-2)", "Reason"]
    ]
)

Semantic scoring columns added.

,Question,Model Answer,Semantic Score (0-2),Reason
0,What is a shell in Linux?,<think>\n\n</think>\n\nA shell is a user inter...,None,
1,What does the Linux command pwd show?,"<think>\n\n</think>\n\npwd stands for ""print w...",None,
2,What does the Linux command ls do?,<think>\n\n</think>\n\nThe ls command lists th...,None,
3,What does the Linux command cd do?,<think>\n\n</think>\n\nThe cd command changes ...,None,
4,What does chmod do in Linux?,<think>\n\n</think>\n\nchmod changes the permi...,None,
5,What does ps show in Linux?,<think>\n\n</think>\n\nps shows information ab...,None,
6,What does kill do in Linux?,<think>\n\n</think>\n\nkill sends a signal to ...,None,
7,What is fork followed by exec used for?,<think>\n\n</think>\n\nFork creates a child pr...,None,
8,What is a shell pipeline?,<think>\n\n</think>\n\nA shell pipeline connec...,None,
9,What is the root directory in Linux?,<think>\n\n</think>\n\nThe root directory is t...,None,
10,What is protection in an operating system?,<think>\n\n</think>\n\nProtection is the mecha...,None,
11,What is authentication?,<think>\n\n</think>\n\nAuthentication is the p...,None,
12,What is authorization?,<think>\n\n</think>\n\nAuthorization determine...,None,
13,What is an access-control list?,<think>\n\n</think>\n\nAn access-control list ...,None,
14,What is the principle of least privilege?,<think>\n\n</think>\n\nThe principle of least ...,None,
15,What is a privilege escalation attack?,<think>\n\n</think>\n\nPrivilege escalation oc...,None,
16,Why should operating systems isolate processes?,<think>\n\n</think>\n\nIsolation prevents one ...,None,
17,What is a secure boot concept?,<think>\n\n</think>\n\nSecure boot ensures tha...,None,
18,What is an operating-system vulnerability?,<think>\n\n</think>\n\nAn operating-system vul...,None,
19,Why are software updates important for operati...,<think>\n\n</think>\n\nSoftware updates often ...,None,
20,What is a distributed operating system?,<think>\n\n</think>\n\nA distributed operating...,None,
21,What is a real-time scheduling deadline?,<think>\n\n</think>\n\nA deadline is the lates...,None,
22,What is hard real-time scheduling?,<think>\n\n</think>\n\nHard real-time scheduli...,None,
23,What is soft real-time scheduling?,<think>\n\n</think>\n\nSoft real-time scheduli...,None,
24,What is symmetric multiprocessing?,<think>\n\n</think>\n\nSymmetric multiprocessi...,None,
25,What is processor affinity?,<think>\n\n</think>\n\nProcessor affinity is t...,None,
26,What is load balancing in multiprocessor systems?,<think>\n\n</think>\n\nLoad balancing distribu...,None,
27,What is NUMA?,<think>\n\n</think>\n\nNUMA stands for Non-Uni...,None,
28,What is an embedded operating system?,<think>\n\n</think>\n\nAn embedded operating s...,None,
29,What is an OS API?,<think>\n\n</think>\n\nAn OS API provides a pr...,None,

In [ ]:
scores = [
    2,  # 1  Shell
    2,  # 2  pwd
    2,  # 3  ls
    2,  # 4  cd
    2,  # 5  chmod
    2,  # 6  ps
    2,  # 7  kill
    2,  # 8  fork + exec
    2,  # 9  shell pipeline
    2,  # 10 root directory
    2,  # 11 protection
    2,  # 12 authentication
    2,  # 13 authorization
    2,  # 14 access-control list
    2,  # 15 least privilege
    2,  # 16 privilege escalation
    2,  # 17 process isolation
    2,  # 18 secure boot
    1,  # 19 OS vulnerability - correct core idea, less complete
    2,  # 20 software updates
    2,  # 21 distributed OS
    2,  # 22 real-time deadline
    2,  # 23 hard real-time
    2,  # 24 soft real-time
    2,  # 25 SMP
    2,  # 26 processor affinity
    2,  # 27 load balancing
    2,  # 28 NUMA
    2,  # 29 embedded OS
    2   # 30 OS API
]

reasons = [
    "Correct definition of a shell.",
    "Correctly explains pwd.",
    "Correctly explains ls.",
    "Correctly explains cd.",
    "Correctly explains chmod and permissions.",
    "Correctly explains ps and process information.",
    "Correctly explains that kill sends a signal to a process.",
    "Correctly explains fork followed by exec.",
    "Correctly explains a shell pipeline.",
    "Correctly identifies / as the root directory.",
    "Correctly explains OS protection.",
    "Correctly explains authentication.",
    "Correctly explains authorization.",
    "Correctly explains an access-control list.",
    "Correctly explains least privilege.",
    "Correctly explains privilege escalation.",
    "Correctly explains the purpose of process isolation.",
    "Correctly explains the purpose of secure boot.",
    "Core idea is correct, but the answer is less complete than the expected answer.",
    "Correctly explains the security importance of updates.",
    "Correctly explains a distributed operating system.",
    "Correctly explains a real-time deadline.",
    "Correctly explains hard real-time scheduling.",
    "Correctly explains soft real-time scheduling.",
    "Correctly explains symmetric multiprocessing.",
    "Correctly explains processor affinity.",
    "Correctly explains load balancing.",
    "Correctly explains NUMA.",
    "Correctly explains an embedded operating system.",
    "Correctly explains an OS API."
]

evaluation_df["Semantic Score (0-2)"] = scores
evaluation_df["Reason"] = reasons

total_score = sum(scores)
max_score = len(scores) * 2
semantic_score = (total_score / max_score) * 100

print("===================================")
print("SEMANTIC EVALUATION")
print("===================================")
print(f"Test questions: {len(scores)}")
print(f"Total score: {total_score}/{max_score}")
print(f"Semantic Score: {semantic_score:.2f}%")
print("===================================")

display(
    evaluation_df[
        ["Question", "Semantic Score (0-2)", "Reason"]
    ]
)

===================================
SEMANTIC EVALUATION
===================================
Test questions: 30
Total score: 59/60
Semantic Score: 98.33%
===================================

,Question,Semantic Score (0-2),Reason
0,What is a shell in Linux?,2,Correct definition of a shell.
1,What does the Linux command pwd show?,2,Correctly explains pwd.
2,What does the Linux command ls do?,2,Correctly explains ls.
3,What does the Linux command cd do?,2,Correctly explains cd.
4,What does chmod do in Linux?,2,Correctly explains chmod and permissions.
5,What does ps show in Linux?,2,Correctly explains ps and process information.
6,What does kill do in Linux?,2,Correctly explains that kill sends a signal to...
7,What is fork followed by exec used for?,2,Correctly explains fork followed by exec.
8,What is a shell pipeline?,2,Correctly explains a shell pipeline.
9,What is the root directory in Linux?,2,Correctly identifies / as the root directory.
10,What is protection in an operating system?,2,Correctly explains OS protection.
11,What is authentication?,2,Correctly explains authentication.
12,What is authorization?,2,Correctly explains authorization.
13,What is an access-control list?,2,Correctly explains an access-control list.
14,What is the principle of least privilege?,2,Correctly explains least privilege.
15,What is a privilege escalation attack?,2,Correctly explains privilege escalation.
16,Why should operating systems isolate processes?,2,Correctly explains the purpose of process isol...
17,What is a secure boot concept?,2,Correctly explains the purpose of secure boot.
18,What is an operating-system vulnerability?,1,"Core idea is correct, but the answer is less c..."
19,Why are software updates important for operati...,2,Correctly explains the security importance of ...
20,What is a distributed operating system?,2,Correctly explains a distributed operating sys...
21,What is a real-time scheduling deadline?,2,Correctly explains a real-time deadline.
22,What is hard real-time scheduling?,2,Correctly explains hard real-time scheduling.
23,What is soft real-time scheduling?,2,Correctly explains soft real-time scheduling.
24,What is symmetric multiprocessing?,2,Correctly explains symmetric multiprocessing.
25,What is processor affinity?,2,Correctly explains processor affinity.
26,What is load balancing in multiprocessor systems?,2,Correctly explains load balancing.
27,What is NUMA?,2,Correctly explains NUMA.
28,What is an embedded operating system?,2,Correctly explains an embedded operating system.
29,What is an OS API?,2,Correctly explains an OS API.

In [ ]:
# Final evaluation statistics

score_counts = evaluation_df["Semantic Score (0-2)"].value_counts().sort_index()

total_score = evaluation_df["Semantic Score (0-2)"].sum()
max_score = len(evaluation_df) * 2
semantic_score = (total_score / max_score) * 100

print("======================================")
print("     OSTutorLLM FINAL EVALUATION")
print("======================================")
print(f"Test questions        : {len(evaluation_df)}")
print(f"Score 2 (Fully correct): {score_counts.get(2, 0)}")
print(f"Score 1 (Partially correct): {score_counts.get(1, 0)}")
print(f"Score 0 (Incorrect)   : {score_counts.get(0, 0)}")
print(f"Total score           : {total_score}/{max_score}")
print(f"Semantic score        : {semantic_score:.2f}%")
print("======================================")

# Save complete evaluation
FINAL_EVAL_FILE = (
    "/content/drive/MyDrive/OSTutorLLM/"
    "ostutorllm_final_30_question_evaluation.csv"
)

evaluation_df.to_csv(FINAL_EVAL_FILE, index=False)

print("\nEvaluation saved to:")
print(FINAL_EVAL_FILE)

======================================
     OSTutorLLM FINAL EVALUATION
======================================
Test questions        : 30
Score 2 (Fully correct): 29
Score 1 (Partially correct): 1
Score 0 (Incorrect)   : 0
Total score           : 59/60
Semantic score        : 98.33%
======================================

Evaluation saved to:
/content/drive/MyDrive/OSTutorLLM/ostutorllm_final_30_question_evaluation.csv